// Code generated by MockGen. DO NOT EDIT.
// Source: /home/suresh/dev/NimbusU/NimbusU-backend/services/course-service/internal/domain/repository.go
//
// Generated by this command:
//
//	mockgen -source=/home/suresh/dev/NimbusU/NimbusU-backend/services/course-service/internal/domain/repository.go -destination=/home/suresh/dev/NimbusU/NimbusU-backend/services/course-service/internal/mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/SureshAmal/NimbusU-backend/services/course-service/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDepartmentRepository is a mock of DepartmentRepository interface.
type MockDepartmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDepartmentRepositoryMockRecorder
	isgomock struct{}
}

// MockDepartmentRepositoryMockRecorder is the mock recorder for MockDepartmentRepository.
type MockDepartmentRepositoryMockRecorder struct {
	mock *MockDepartmentRepository
}

// NewMockDepartmentRepository creates a new mock instance.
func NewMockDepartmentRepository(ctrl *gomock.Controller) *MockDepartmentRepository {
	mock := &MockDepartmentRepository{ctrl: ctrl}
	mock.recorder = &MockDepartmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepartmentRepository) EXPECT() *MockDepartmentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDepartmentRepository) Create(ctx context.Context, department *domain.Department) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, department)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDepartmentRepositoryMockRecorder) Create(ctx, department any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDepartmentRepository)(nil).Create), ctx, department)
}

// Delete mocks base method.
func (m *MockDepartmentRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDepartmentRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDepartmentRepository)(nil).Delete), ctx, id)
}

// GetByCode mocks base method.
func (m *MockDepartmentRepository) GetByCode(ctx context.Context, code string) (*domain.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*domain.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockDepartmentRepositoryMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockDepartmentRepository)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockDepartmentRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDepartmentRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDepartmentRepository)(nil).GetByID), ctx, id)
}

// GetWithDetails mocks base method.
func (m *MockDepartmentRepository) GetWithDetails(ctx context.Context, id uuid.UUID) (*domain.DepartmentWithDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithDetails", ctx, id)
	ret0, _ := ret[0].(*domain.DepartmentWithDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithDetails indicates an expected call of GetWithDetails.
func (mr *MockDepartmentRepositoryMockRecorder) GetWithDetails(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithDetails", reflect.TypeOf((*MockDepartmentRepository)(nil).GetWithDetails), ctx, id)
}

// List mocks base method.
func (m *MockDepartmentRepository) List(ctx context.Context, filter domain.DepartmentFilter, limit, offset int) ([]*domain.Department, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, limit, offset)
	ret0, _ := ret[0].([]*domain.Department)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockDepartmentRepositoryMockRecorder) List(ctx, filter, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDepartmentRepository)(nil).List), ctx, filter, limit, offset)
}

// Update mocks base method.
func (m *MockDepartmentRepository) Update(ctx context.Context, department *domain.Department) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, department)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDepartmentRepositoryMockRecorder) Update(ctx, department any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDepartmentRepository)(nil).Update), ctx, department)
}

// MockProgramRepository is a mock of ProgramRepository interface.
type MockProgramRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProgramRepositoryMockRecorder
	isgomock struct{}
}

// MockProgramRepositoryMockRecorder is the mock recorder for MockProgramRepository.
type MockProgramRepositoryMockRecorder struct {
	mock *MockProgramRepository
}

// NewMockProgramRepository creates a new mock instance.
func NewMockProgramRepository(ctrl *gomock.Controller) *MockProgramRepository {
	mock := &MockProgramRepository{ctrl: ctrl}
	mock.recorder = &MockProgramRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProgramRepository) EXPECT() *MockProgramRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProgramRepository) Create(ctx context.Context, program *domain.Program) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, program)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProgramRepositoryMockRecorder) Create(ctx, program any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProgramRepository)(nil).Create), ctx, program)
}

// Delete mocks base method.
func (m *MockProgramRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProgramRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProgramRepository)(nil).Delete), ctx, id)
}

// GetByCode mocks base method.
func (m *MockProgramRepository) GetByCode(ctx context.Context, code string) (*domain.Program, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*domain.Program)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockProgramRepositoryMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockProgramRepository)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockProgramRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Program, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Program)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProgramRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProgramRepository)(nil).GetByID), ctx, id)
}

// GetWithDepartment mocks base method.
func (m *MockProgramRepository) GetWithDepartment(ctx context.Context, id uuid.UUID) (*domain.ProgramWithDepartment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithDepartment", ctx, id)
	ret0, _ := ret[0].(*domain.ProgramWithDepartment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithDepartment indicates an expected call of GetWithDepartment.
func (mr *MockProgramRepositoryMockRecorder) GetWithDepartment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithDepartment", reflect.TypeOf((*MockProgramRepository)(nil).GetWithDepartment), ctx, id)
}

// List mocks base method.
func (m *MockProgramRepository) List(ctx context.Context, filter domain.ProgramFilter, limit, offset int) ([]*domain.ProgramWithDepartment, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, limit, offset)
	ret0, _ := ret[0].([]*domain.ProgramWithDepartment)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockProgramRepositoryMockRecorder) List(ctx, filter, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProgramRepository)(nil).List), ctx, filter, limit, offset)
}

// Update mocks base method.
func (m *MockProgramRepository) Update(ctx context.Context, program *domain.Program) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, program)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProgramRepositoryMockRecorder) Update(ctx, program any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProgramRepository)(nil).Update), ctx, program)
}

// MockSubjectRepository is a mock of SubjectRepository interface.
type MockSubjectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubjectRepositoryMockRecorder
	isgomock struct{}
}

// MockSubjectRepositoryMockRecorder is the mock recorder for MockSubjectRepository.
type MockSubjectRepositoryMockRecorder struct {
	mock *MockSubjectRepository
}

// NewMockSubjectRepository creates a new mock instance.
func NewMockSubjectRepository(ctrl *gomock.Controller) *MockSubjectRepository {
	mock := &MockSubjectRepository{ctrl: ctrl}
	mock.recorder = &MockSubjectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubjectRepository) EXPECT() *MockSubjectRepositoryMockRecorder {
	return m.recorder
}

// AddCorequisite mocks base method.
func (m *MockSubjectRepository) AddCorequisite(ctx context.Context, subjectID, corequisiteID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCorequisite", ctx, subjectID, corequisiteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCorequisite indicates an expected call of AddCorequisite.
func (mr *MockSubjectRepositoryMockRecorder) AddCorequisite(ctx, subjectID, corequisiteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCorequisite", reflect.TypeOf((*MockSubjectRepository)(nil).AddCorequisite), ctx, subjectID, corequisiteID)
}

// AddPrerequisite mocks base method.
func (m *MockSubjectRepository) AddPrerequisite(ctx context.Context, subjectID, prerequisiteID uuid.UUID, isMandatory bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPrerequisite", ctx, subjectID, prerequisiteID, isMandatory)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPrerequisite indicates an expected call of AddPrerequisite.
func (mr *MockSubjectRepositoryMockRecorder) AddPrerequisite(ctx, subjectID, prerequisiteID, isMandatory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPrerequisite", reflect.TypeOf((*MockSubjectRepository)(nil).AddPrerequisite), ctx, subjectID, prerequisiteID, isMandatory)
}

// Create mocks base method.
func (m *MockSubjectRepository) Create(ctx context.Context, subject *domain.Subject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, subject)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSubjectRepositoryMockRecorder) Create(ctx, subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSubjectRepository)(nil).Create), ctx, subject)
}

// Delete mocks base method.
func (m *MockSubjectRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSubjectRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSubjectRepository)(nil).Delete), ctx, id)
}

// GetByCode mocks base method.
func (m *MockSubjectRepository) GetByCode(ctx context.Context, code string) (*domain.Subject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*domain.Subject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockSubjectRepositoryMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockSubjectRepository)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockSubjectRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Subject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Subject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSubjectRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSubjectRepository)(nil).GetByID), ctx, id)
}

// GetCorequisites mocks base method.
func (m *MockSubjectRepository) GetCorequisites(ctx context.Context, subjectID uuid.UUID) ([]domain.SubjectBasic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCorequisites", ctx, subjectID)
	ret0, _ := ret[0].([]domain.SubjectBasic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCorequisites indicates an expected call of GetCorequisites.
func (mr *MockSubjectRepositoryMockRecorder) GetCorequisites(ctx, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCorequisites", reflect.TypeOf((*MockSubjectRepository)(nil).GetCorequisites), ctx, subjectID)
}

// GetPrerequisites mocks base method.
func (m *MockSubjectRepository) GetPrerequisites(ctx context.Context, subjectID uuid.UUID) ([]domain.SubjectPrerequisite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrerequisites", ctx, subjectID)
	ret0, _ := ret[0].([]domain.SubjectPrerequisite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrerequisites indicates an expected call of GetPrerequisites.
func (mr *MockSubjectRepositoryMockRecorder) GetPrerequisites(ctx, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrerequisites", reflect.TypeOf((*MockSubjectRepository)(nil).GetPrerequisites), ctx, subjectID)
}

// GetWithDetails mocks base method.
func (m *MockSubjectRepository) GetWithDetails(ctx context.Context, id uuid.UUID) (*domain.SubjectWithDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithDetails", ctx, id)
	ret0, _ := ret[0].(*domain.SubjectWithDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithDetails indicates an expected call of GetWithDetails.
func (mr *MockSubjectRepositoryMockRecorder) GetWithDetails(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithDetails", reflect.TypeOf((*MockSubjectRepository)(nil).GetWithDetails), ctx, id)
}

// List mocks base method.
func (m *MockSubjectRepository) List(ctx context.Context, filter domain.SubjectFilter, limit, offset int) ([]*domain.Subject, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, limit, offset)
	ret0, _ := ret[0].([]*domain.Subject)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockSubjectRepositoryMockRecorder) List(ctx, filter, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSubjectRepository)(nil).List), ctx, filter, limit, offset)
}

// RemoveCorequisite mocks base method.
func (m *MockSubjectRepository) RemoveCorequisite(ctx context.Context, subjectID, corequisiteID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCorequisite", ctx, subjectID, corequisiteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCorequisite indicates an expected call of RemoveCorequisite.
func (mr *MockSubjectRepositoryMockRecorder) RemoveCorequisite(ctx, subjectID, corequisiteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCorequisite", reflect.TypeOf((*MockSubjectRepository)(nil).RemoveCorequisite), ctx, subjectID, corequisiteID)
}

// RemovePrerequisite mocks base method.
func (m *MockSubjectRepository) RemovePrerequisite(ctx context.Context, subjectID, prerequisiteID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePrerequisite", ctx, subjectID, prerequisiteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemovePrerequisite indicates an expected call of RemovePrerequisite.
func (mr *MockSubjectRepositoryMockRecorder) RemovePrerequisite(ctx, subjectID, prerequisiteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePrerequisite", reflect.TypeOf((*MockSubjectRepository)(nil).RemovePrerequisite), ctx, subjectID, prerequisiteID)
}

// Update mocks base method.
func (m *MockSubjectRepository) Update(ctx context.Context, subject *domain.Subject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, subject)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSubjectRepositoryMockRecorder) Update(ctx, subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSubjectRepository)(nil).Update), ctx, subject)
}

// MockSemesterRepository is a mock of SemesterRepository interface.
type MockSemesterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSemesterRepositoryMockRecorder
	isgomock struct{}
}

// MockSemesterRepositoryMockRecorder is the mock recorder for MockSemesterRepository.
type MockSemesterRepositoryMockRecorder struct {
	mock *MockSemesterRepository
}

// NewMockSemesterRepository creates a new mock instance.
func NewMockSemesterRepository(ctrl *gomock.Controller) *MockSemesterRepository {
	mock := &MockSemesterRepository{ctrl: ctrl}
	mock.recorder = &MockSemesterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSemesterRepository) EXPECT() *MockSemesterRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSemesterRepository) Create(ctx context.Context, semester *domain.Semester) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, semester)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSemesterRepositoryMockRecorder) Create(ctx, semester any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSemesterRepository)(nil).Create), ctx, semester)
}

// Delete mocks base method.
func (m *MockSemesterRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSemesterRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSemesterRepository)(nil).Delete), ctx, id)
}

// GetByCode mocks base method.
func (m *MockSemesterRepository) GetByCode(ctx context.Context, code string) (*domain.Semester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*domain.Semester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockSemesterRepositoryMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockSemesterRepository)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockSemesterRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Semester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Semester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSemesterRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSemesterRepository)(nil).GetByID), ctx, id)
}

// GetCurrent mocks base method.
func (m *MockSemesterRepository) GetCurrent(ctx context.Context) (*domain.Semester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrent", ctx)
	ret0, _ := ret[0].(*domain.Semester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrent indicates an expected call of GetCurrent.
func (mr *MockSemesterRepositoryMockRecorder) GetCurrent(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrent", reflect.TypeOf((*MockSemesterRepository)(nil).GetCurrent), ctx)
}

// List mocks base method.
func (m *MockSemesterRepository) List(ctx context.Context, filter domain.SemesterFilter, limit, offset int) ([]*domain.Semester, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, limit, offset)
	ret0, _ := ret[0].([]*domain.Semester)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockSemesterRepositoryMockRecorder) List(ctx, filter, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSemesterRepository)(nil).List), ctx, filter, limit, offset)
}

// SetCurrent mocks base method.
func (m *MockSemesterRepository) SetCurrent(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCurrent", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCurrent indicates an expected call of SetCurrent.
func (mr *MockSemesterRepositoryMockRecorder) SetCurrent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCurrent", reflect.TypeOf((*MockSemesterRepository)(nil).SetCurrent), ctx, id)
}

// Update mocks base method.
func (m *MockSemesterRepository) Update(ctx context.Context, semester *domain.Semester) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, semester)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSemesterRepositoryMockRecorder) Update(ctx, semester any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSemesterRepository)(nil).Update), ctx, semester)
}

// MockCourseRepository is a mock of CourseRepository interface.
type MockCourseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCourseRepositoryMockRecorder
	isgomock struct{}
}

// MockCourseRepositoryMockRecorder is the mock recorder for MockCourseRepository.
type MockCourseRepositoryMockRecorder struct {
	mock *MockCourseRepository
}

// NewMockCourseRepository creates a new mock instance.
func NewMockCourseRepository(ctrl *gomock.Controller) *MockCourseRepository {
	mock := &MockCourseRepository{ctrl: ctrl}
	mock.recorder = &MockCourseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCourseRepository) EXPECT() *MockCourseRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCourseRepository) Create(ctx context.Context, course *domain.Course) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, course)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCourseRepositoryMockRecorder) Create(ctx, course any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCourseRepository)(nil).Create), ctx, course)
}

// DecrementEnrollment mocks base method.
func (m *MockCourseRepository) DecrementEnrollment(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementEnrollment", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementEnrollment indicates an expected call of DecrementEnrollment.
func (mr *MockCourseRepositoryMockRecorder) DecrementEnrollment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementEnrollment", reflect.TypeOf((*MockCourseRepository)(nil).DecrementEnrollment), ctx, id)
}

// Delete mocks base method.
func (m *MockCourseRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCourseRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCourseRepository)(nil).Delete), ctx, id)
}

// GetByCode mocks base method.
func (m *MockCourseRepository) GetByCode(ctx context.Context, code string) (*domain.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*domain.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockCourseRepositoryMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockCourseRepository)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockCourseRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCourseRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCourseRepository)(nil).GetByID), ctx, id)
}

// GetWithDetails mocks base method.
func (m *MockCourseRepository) GetWithDetails(ctx context.Context, id uuid.UUID) (*domain.CourseWithDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithDetails", ctx, id)
	ret0, _ := ret[0].(*domain.CourseWithDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithDetails indicates an expected call of GetWithDetails.
func (mr *MockCourseRepositoryMockRecorder) GetWithDetails(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithDetails", reflect.TypeOf((*MockCourseRepository)(nil).GetWithDetails), ctx, id)
}

// IncrementEnrollment mocks base method.
func (m *MockCourseRepository) IncrementEnrollment(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementEnrollment", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementEnrollment indicates an expected call of IncrementEnrollment.
func (mr *MockCourseRepositoryMockRecorder) IncrementEnrollment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementEnrollment", reflect.TypeOf((*MockCourseRepository)(nil).IncrementEnrollment), ctx, id)
}

// List mocks base method.
func (m *MockCourseRepository) List(ctx context.Context, filter domain.CourseFilter, limit, offset int) ([]*domain.CourseWithDetails, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, limit, offset)
	ret0, _ := ret[0].([]*domain.CourseWithDetails)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockCourseRepositoryMockRecorder) List(ctx, filter, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCourseRepository)(nil).List), ctx, filter, limit, offset)
}

// Update mocks base method.
func (m *MockCourseRepository) Update(ctx context.Context, course *domain.Course) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, course)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCourseRepositoryMockRecorder) Update(ctx, course any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCourseRepository)(nil).Update), ctx, course)
}

// UpdateStatus mocks base method.
func (m *MockCourseRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockCourseRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockCourseRepository)(nil).UpdateStatus), ctx, id, status)
}

// MockFacultyRepository is a mock of FacultyRepository interface.
type MockFacultyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFacultyRepositoryMockRecorder
	isgomock struct{}
}

// MockFacultyRepositoryMockRecorder is the mock recorder for MockFacultyRepository.
type MockFacultyRepositoryMockRecorder struct {
	mock *MockFacultyRepository
}

// NewMockFacultyRepository creates a new mock instance.
func NewMockFacultyRepository(ctrl *gomock.Controller) *MockFacultyRepository {
	mock := &MockFacultyRepository{ctrl: ctrl}
	mock.recorder = &MockFacultyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFacultyRepository) EXPECT() *MockFacultyRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFacultyRepository) Create(ctx context.Context, faculty *domain.Faculty) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, faculty)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFacultyRepositoryMockRecorder) Create(ctx, faculty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFacultyRepository)(nil).Create), ctx, faculty)
}

// Delete mocks base method.
func (m *MockFacultyRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFacultyRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFacultyRepository)(nil).Delete), ctx, id)
}

// GetByEmployeeID mocks base method.
func (m *MockFacultyRepository) GetByEmployeeID(ctx context.Context, employeeID string) (*domain.Faculty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmployeeID", ctx, employeeID)
	ret0, _ := ret[0].(*domain.Faculty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmployeeID indicates an expected call of GetByEmployeeID.
func (mr *MockFacultyRepositoryMockRecorder) GetByEmployeeID(ctx, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmployeeID", reflect.TypeOf((*MockFacultyRepository)(nil).GetByEmployeeID), ctx, employeeID)
}

// GetByID mocks base method.
func (m *MockFacultyRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Faculty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Faculty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockFacultyRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockFacultyRepository)(nil).GetByID), ctx, id)
}

// GetByUserID mocks base method.
func (m *MockFacultyRepository) GetByUserID(ctx context.Context, userID uuid.UUID) (*domain.Faculty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.Faculty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockFacultyRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockFacultyRepository)(nil).GetByUserID), ctx, userID)
}

// GetWithDetails mocks base method.
func (m *MockFacultyRepository) GetWithDetails(ctx context.Context, id uuid.UUID) (*domain.FacultyWithDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithDetails", ctx, id)
	ret0, _ := ret[0].(*domain.FacultyWithDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithDetails indicates an expected call of GetWithDetails.
func (mr *MockFacultyRepositoryMockRecorder) GetWithDetails(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithDetails", reflect.TypeOf((*MockFacultyRepository)(nil).GetWithDetails), ctx, id)
}

// List mocks base method.
func (m *MockFacultyRepository) List(ctx context.Context, filter domain.FacultyFilter, limit, offset int) ([]*domain.FacultyWithDetails, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, limit, offset)
	ret0, _ := ret[0].([]*domain.FacultyWithDetails)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockFacultyRepositoryMockRecorder) List(ctx, filter, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFacultyRepository)(nil).List), ctx, filter, limit, offset)
}

// Update mocks base method.
func (m *MockFacultyRepository) Update(ctx context.Context, faculty *domain.Faculty) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, faculty)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockFacultyRepositoryMockRecorder) Update(ctx, faculty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFacultyRepository)(nil).Update), ctx, faculty)
}

// MockStudentRepository is a mock of StudentRepository interface.
type MockStudentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStudentRepositoryMockRecorder
	isgomock struct{}
}

// MockStudentRepositoryMockRecorder is the mock recorder for MockStudentRepository.
type MockStudentRepositoryMockRecorder struct {
	mock *MockStudentRepository
}

// NewMockStudentRepository creates a new mock instance.
func NewMockStudentRepository(ctrl *gomock.Controller) *MockStudentRepository {
	mock := &MockStudentRepository{ctrl: ctrl}
	mock.recorder = &MockStudentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudentRepository) EXPECT() *MockStudentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStudentRepository) Create(ctx context.Context, student *domain.Student) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, student)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStudentRepositoryMockRecorder) Create(ctx, student any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStudentRepository)(nil).Create), ctx, student)
}

// Delete mocks base method.
func (m *MockStudentRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStudentRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStudentRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockStudentRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockStudentRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockStudentRepository)(nil).GetByID), ctx, id)
}

// GetByRegistrationNumber mocks base method.
func (m *MockStudentRepository) GetByRegistrationNumber(ctx context.Context, regNo string) (*domain.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRegistrationNumber", ctx, regNo)
	ret0, _ := ret[0].(*domain.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRegistrationNumber indicates an expected call of GetByRegistrationNumber.
func (mr *MockStudentRepositoryMockRecorder) GetByRegistrationNumber(ctx, regNo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRegistrationNumber", reflect.TypeOf((*MockStudentRepository)(nil).GetByRegistrationNumber), ctx, regNo)
}

// GetByUserID mocks base method.
func (m *MockStudentRepository) GetByUserID(ctx context.Context, userID uuid.UUID) (*domain.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockStudentRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockStudentRepository)(nil).GetByUserID), ctx, userID)
}

// GetWithDetails mocks base method.
func (m *MockStudentRepository) GetWithDetails(ctx context.Context, id uuid.UUID) (*domain.StudentWithDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithDetails", ctx, id)
	ret0, _ := ret[0].(*domain.StudentWithDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithDetails indicates an expected call of GetWithDetails.
func (mr *MockStudentRepositoryMockRecorder) GetWithDetails(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithDetails", reflect.TypeOf((*MockStudentRepository)(nil).GetWithDetails), ctx, id)
}

// List mocks base method.
func (m *MockStudentRepository) List(ctx context.Context, filter domain.StudentFilter, limit, offset int) ([]*domain.StudentWithDetails, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, limit, offset)
	ret0, _ := ret[0].([]*domain.StudentWithDetails)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockStudentRepositoryMockRecorder) List(ctx, filter, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStudentRepository)(nil).List), ctx, filter, limit, offset)
}

// Update mocks base method.
func (m *MockStudentRepository) Update(ctx context.Context, student *domain.Student) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, student)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStudentRepositoryMockRecorder) Update(ctx, student any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStudentRepository)(nil).Update), ctx, student)
}

// UpdateSemester mocks base method.
func (m *MockStudentRepository) UpdateSemester(ctx context.Context, id uuid.UUID, semester int, cgpa *float64, credits int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSemester", ctx, id, semester, cgpa, credits)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSemester indicates an expected call of UpdateSemester.
func (mr *MockStudentRepositoryMockRecorder) UpdateSemester(ctx, id, semester, cgpa, credits any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSemester", reflect.TypeOf((*MockStudentRepository)(nil).UpdateSemester), ctx, id, semester, cgpa, credits)
}

// MockFacultyCourseRepository is a mock of FacultyCourseRepository interface.
type MockFacultyCourseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFacultyCourseRepositoryMockRecorder
	isgomock struct{}
}

// MockFacultyCourseRepositoryMockRecorder is the mock recorder for MockFacultyCourseRepository.
type MockFacultyCourseRepositoryMockRecorder struct {
	mock *MockFacultyCourseRepository
}

// NewMockFacultyCourseRepository creates a new mock instance.
func NewMockFacultyCourseRepository(ctrl *gomock.Controller) *MockFacultyCourseRepository {
	mock := &MockFacultyCourseRepository{ctrl: ctrl}
	mock.recorder = &MockFacultyCourseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFacultyCourseRepository) EXPECT() *MockFacultyCourseRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFacultyCourseRepository) Create(ctx context.Context, fc *domain.FacultyCourse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, fc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFacultyCourseRepositoryMockRecorder) Create(ctx, fc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFacultyCourseRepository)(nil).Create), ctx, fc)
}

// Delete mocks base method.
func (m *MockFacultyCourseRepository) Delete(ctx context.Context, facultyID, courseID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, facultyID, courseID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFacultyCourseRepositoryMockRecorder) Delete(ctx, facultyID, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFacultyCourseRepository)(nil).Delete), ctx, facultyID, courseID)
}

// GetAssignment mocks base method.
func (m *MockFacultyCourseRepository) GetAssignment(ctx context.Context, facultyID, courseID uuid.UUID) (*domain.FacultyCourse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssignment", ctx, facultyID, courseID)
	ret0, _ := ret[0].(*domain.FacultyCourse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssignment indicates an expected call of GetAssignment.
func (mr *MockFacultyCourseRepositoryMockRecorder) GetAssignment(ctx, facultyID, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssignment", reflect.TypeOf((*MockFacultyCourseRepository)(nil).GetAssignment), ctx, facultyID, courseID)
}

// GetByID mocks base method.
func (m *MockFacultyCourseRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.FacultyCourse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.FacultyCourse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockFacultyCourseRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockFacultyCourseRepository)(nil).GetByID), ctx, id)
}

// IsPrimaryFaculty mocks base method.
func (m *MockFacultyCourseRepository) IsPrimaryFaculty(ctx context.Context, facultyID, courseID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPrimaryFaculty", ctx, facultyID, courseID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsPrimaryFaculty indicates an expected call of IsPrimaryFaculty.
func (mr *MockFacultyCourseRepositoryMockRecorder) IsPrimaryFaculty(ctx, facultyID, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPrimaryFaculty", reflect.TypeOf((*MockFacultyCourseRepository)(nil).IsPrimaryFaculty), ctx, facultyID, courseID)
}

// ListByCourse mocks base method.
func (m *MockFacultyCourseRepository) ListByCourse(ctx context.Context, courseID uuid.UUID) ([]*domain.FacultyCourseWithDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCourse", ctx, courseID)
	ret0, _ := ret[0].([]*domain.FacultyCourseWithDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByCourse indicates an expected call of ListByCourse.
func (mr *MockFacultyCourseRepositoryMockRecorder) ListByCourse(ctx, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCourse", reflect.TypeOf((*MockFacultyCourseRepository)(nil).ListByCourse), ctx, courseID)
}

// ListByFaculty mocks base method.
func (m *MockFacultyCourseRepository) ListByFaculty(ctx context.Context, facultyID uuid.UUID, semesterID *uuid.UUID) ([]*domain.FacultyCourse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByFaculty", ctx, facultyID, semesterID)
	ret0, _ := ret[0].([]*domain.FacultyCourse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByFaculty indicates an expected call of ListByFaculty.
func (mr *MockFacultyCourseRepositoryMockRecorder) ListByFaculty(ctx, facultyID, semesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByFaculty", reflect.TypeOf((*MockFacultyCourseRepository)(nil).ListByFaculty), ctx, facultyID, semesterID)
}

// Update mocks base method.
func (m *MockFacultyCourseRepository) Update(ctx context.Context, fc *domain.FacultyCourse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, fc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockFacultyCourseRepositoryMockRecorder) Update(ctx, fc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFacultyCourseRepository)(nil).Update), ctx, fc)
}

// MockEnrollmentRepository is a mock of EnrollmentRepository interface.
type MockEnrollmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEnrollmentRepositoryMockRecorder
	isgomock struct{}
}

// MockEnrollmentRepositoryMockRecorder is the mock recorder for MockEnrollmentRepository.
type MockEnrollmentRepositoryMockRecorder struct {
	mock *MockEnrollmentRepository
}

// NewMockEnrollmentRepository creates a new mock instance.
func NewMockEnrollmentRepository(ctrl *gomock.Controller) *MockEnrollmentRepository {
	mock := &MockEnrollmentRepository{ctrl: ctrl}
	mock.recorder = &MockEnrollmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnrollmentRepository) EXPECT() *MockEnrollmentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEnrollmentRepository) Create(ctx context.Context, enrollment *domain.CourseEnrollment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, enrollment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEnrollmentRepositoryMockRecorder) Create(ctx, enrollment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEnrollmentRepository)(nil).Create), ctx, enrollment)
}

// Delete mocks base method.
func (m *MockEnrollmentRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEnrollmentRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEnrollmentRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockEnrollmentRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.CourseEnrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.CourseEnrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEnrollmentRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEnrollmentRepository)(nil).GetByID), ctx, id)
}

// GetByStudentAndCourse mocks base method.
func (m *MockEnrollmentRepository) GetByStudentAndCourse(ctx context.Context, studentID, courseID uuid.UUID) (*domain.CourseEnrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByStudentAndCourse", ctx, studentID, courseID)
	ret0, _ := ret[0].(*domain.CourseEnrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByStudentAndCourse indicates an expected call of GetByStudentAndCourse.
func (mr *MockEnrollmentRepositoryMockRecorder) GetByStudentAndCourse(ctx, studentID, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStudentAndCourse", reflect.TypeOf((*MockEnrollmentRepository)(nil).GetByStudentAndCourse), ctx, studentID, courseID)
}

// GetEnrollmentSummary mocks base method.
func (m *MockEnrollmentRepository) GetEnrollmentSummary(ctx context.Context, courseID uuid.UUID) (int, int, int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnrollmentSummary", ctx, courseID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(int)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// GetEnrollmentSummary indicates an expected call of GetEnrollmentSummary.
func (mr *MockEnrollmentRepositoryMockRecorder) GetEnrollmentSummary(ctx, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnrollmentSummary", reflect.TypeOf((*MockEnrollmentRepository)(nil).GetEnrollmentSummary), ctx, courseID)
}

// GetNextWaitlistPosition mocks base method.
func (m *MockEnrollmentRepository) GetNextWaitlistPosition(ctx context.Context, courseID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextWaitlistPosition", ctx, courseID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextWaitlistPosition indicates an expected call of GetNextWaitlistPosition.
func (mr *MockEnrollmentRepositoryMockRecorder) GetNextWaitlistPosition(ctx, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextWaitlistPosition", reflect.TypeOf((*MockEnrollmentRepository)(nil).GetNextWaitlistPosition), ctx, courseID)
}

// ListByCourse mocks base method.
func (m *MockEnrollmentRepository) ListByCourse(ctx context.Context, courseID uuid.UUID, status *string, limit, offset int) ([]*domain.EnrollmentWithDetails, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCourse", ctx, courseID, status, limit, offset)
	ret0, _ := ret[0].([]*domain.EnrollmentWithDetails)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByCourse indicates an expected call of ListByCourse.
func (mr *MockEnrollmentRepositoryMockRecorder) ListByCourse(ctx, courseID, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCourse", reflect.TypeOf((*MockEnrollmentRepository)(nil).ListByCourse), ctx, courseID, status, limit, offset)
}

// ListByStudent mocks base method.
func (m *MockEnrollmentRepository) ListByStudent(ctx context.Context, filter domain.EnrollmentFilter, limit, offset int) ([]*domain.EnrollmentWithDetails, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByStudent", ctx, filter, limit, offset)
	ret0, _ := ret[0].([]*domain.EnrollmentWithDetails)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByStudent indicates an expected call of ListByStudent.
func (mr *MockEnrollmentRepositoryMockRecorder) ListByStudent(ctx, filter, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStudent", reflect.TypeOf((*MockEnrollmentRepository)(nil).ListByStudent), ctx, filter, limit, offset)
}

// PromoteFromWaitlist mocks base method.
func (m *MockEnrollmentRepository) PromoteFromWaitlist(ctx context.Context, courseID uuid.UUID) (*domain.CourseEnrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromoteFromWaitlist", ctx, courseID)
	ret0, _ := ret[0].(*domain.CourseEnrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PromoteFromWaitlist indicates an expected call of PromoteFromWaitlist.
func (mr *MockEnrollmentRepositoryMockRecorder) PromoteFromWaitlist(ctx, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromoteFromWaitlist", reflect.TypeOf((*MockEnrollmentRepository)(nil).PromoteFromWaitlist), ctx, courseID)
}

// Update mocks base method.
func (m *MockEnrollmentRepository) Update(ctx context.Context, enrollment *domain.CourseEnrollment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, enrollment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockEnrollmentRepositoryMockRecorder) Update(ctx, enrollment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEnrollmentRepository)(nil).Update), ctx, enrollment)
}

// MockCalendarRepository is a mock of CalendarRepository interface.
type MockCalendarRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCalendarRepositoryMockRecorder
	isgomock struct{}
}

// MockCalendarRepositoryMockRecorder is the mock recorder for MockCalendarRepository.
type MockCalendarRepositoryMockRecorder struct {
	mock *MockCalendarRepository
}

// NewMockCalendarRepository creates a new mock instance.
func NewMockCalendarRepository(ctrl *gomock.Controller) *MockCalendarRepository {
	mock := &MockCalendarRepository{ctrl: ctrl}
	mock.recorder = &MockCalendarRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCalendarRepository) EXPECT() *MockCalendarRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCalendarRepository) Create(ctx context.Context, event *domain.AcademicCalendarEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCalendarRepositoryMockRecorder) Create(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCalendarRepository)(nil).Create), ctx, event)
}

// Delete mocks base method.
func (m *MockCalendarRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCalendarRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCalendarRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockCalendarRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.AcademicCalendarEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.AcademicCalendarEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCalendarRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCalendarRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockCalendarRepository) List(ctx context.Context, filter domain.CalendarFilter, limit, offset int) ([]*domain.AcademicCalendarEventWithDetails, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, limit, offset)
	ret0, _ := ret[0].([]*domain.AcademicCalendarEventWithDetails)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockCalendarRepositoryMockRecorder) List(ctx, filter, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCalendarRepository)(nil).List), ctx, filter, limit, offset)
}

// Update mocks base method.
func (m *MockCalendarRepository) Update(ctx context.Context, event *domain.AcademicCalendarEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCalendarRepositoryMockRecorder) Update(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCalendarRepository)(nil).Update), ctx, event)
}
