// Code generated by MockGen. DO NOT EDIT.
// Source: /home/suresh/dev/NimbusU/NimbusU-backend/services/course-service/internal/domain/service.go
//
// Generated by this command:
//
//	mockgen -source=/home/suresh/dev/NimbusU/NimbusU-backend/services/course-service/internal/domain/service.go -destination=/home/suresh/dev/NimbusU/NimbusU-backend/services/course-service/internal/mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/SureshAmal/NimbusU-backend/services/course-service/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDepartmentService is a mock of DepartmentService interface.
type MockDepartmentService struct {
	ctrl     *gomock.Controller
	recorder *MockDepartmentServiceMockRecorder
	isgomock struct{}
}

// MockDepartmentServiceMockRecorder is the mock recorder for MockDepartmentService.
type MockDepartmentServiceMockRecorder struct {
	mock *MockDepartmentService
}

// NewMockDepartmentService creates a new mock instance.
func NewMockDepartmentService(ctrl *gomock.Controller) *MockDepartmentService {
	mock := &MockDepartmentService{ctrl: ctrl}
	mock.recorder = &MockDepartmentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepartmentService) EXPECT() *MockDepartmentServiceMockRecorder {
	return m.recorder
}

// CreateDepartment mocks base method.
func (m *MockDepartmentService) CreateDepartment(ctx context.Context, department *domain.Department) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDepartment", ctx, department)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDepartment indicates an expected call of CreateDepartment.
func (mr *MockDepartmentServiceMockRecorder) CreateDepartment(ctx, department any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDepartment", reflect.TypeOf((*MockDepartmentService)(nil).CreateDepartment), ctx, department)
}

// DeleteDepartment mocks base method.
func (m *MockDepartmentService) DeleteDepartment(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDepartment", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDepartment indicates an expected call of DeleteDepartment.
func (mr *MockDepartmentServiceMockRecorder) DeleteDepartment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDepartment", reflect.TypeOf((*MockDepartmentService)(nil).DeleteDepartment), ctx, id)
}

// GetDepartment mocks base method.
func (m *MockDepartmentService) GetDepartment(ctx context.Context, id uuid.UUID) (*domain.DepartmentWithDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartment", ctx, id)
	ret0, _ := ret[0].(*domain.DepartmentWithDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartment indicates an expected call of GetDepartment.
func (mr *MockDepartmentServiceMockRecorder) GetDepartment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartment", reflect.TypeOf((*MockDepartmentService)(nil).GetDepartment), ctx, id)
}

// ListDepartments mocks base method.
func (m *MockDepartmentService) ListDepartments(ctx context.Context, filter domain.DepartmentFilter, page, limit int) ([]*domain.Department, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDepartments", ctx, filter, page, limit)
	ret0, _ := ret[0].([]*domain.Department)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListDepartments indicates an expected call of ListDepartments.
func (mr *MockDepartmentServiceMockRecorder) ListDepartments(ctx, filter, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDepartments", reflect.TypeOf((*MockDepartmentService)(nil).ListDepartments), ctx, filter, page, limit)
}

// UpdateDepartment mocks base method.
func (m *MockDepartmentService) UpdateDepartment(ctx context.Context, id uuid.UUID, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDepartment", ctx, id, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDepartment indicates an expected call of UpdateDepartment.
func (mr *MockDepartmentServiceMockRecorder) UpdateDepartment(ctx, id, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDepartment", reflect.TypeOf((*MockDepartmentService)(nil).UpdateDepartment), ctx, id, updates)
}

// MockProgramService is a mock of ProgramService interface.
type MockProgramService struct {
	ctrl     *gomock.Controller
	recorder *MockProgramServiceMockRecorder
	isgomock struct{}
}

// MockProgramServiceMockRecorder is the mock recorder for MockProgramService.
type MockProgramServiceMockRecorder struct {
	mock *MockProgramService
}

// NewMockProgramService creates a new mock instance.
func NewMockProgramService(ctrl *gomock.Controller) *MockProgramService {
	mock := &MockProgramService{ctrl: ctrl}
	mock.recorder = &MockProgramServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProgramService) EXPECT() *MockProgramServiceMockRecorder {
	return m.recorder
}

// CreateProgram mocks base method.
func (m *MockProgramService) CreateProgram(ctx context.Context, program *domain.Program) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProgram", ctx, program)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProgram indicates an expected call of CreateProgram.
func (mr *MockProgramServiceMockRecorder) CreateProgram(ctx, program any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProgram", reflect.TypeOf((*MockProgramService)(nil).CreateProgram), ctx, program)
}

// DeleteProgram mocks base method.
func (m *MockProgramService) DeleteProgram(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProgram", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProgram indicates an expected call of DeleteProgram.
func (mr *MockProgramServiceMockRecorder) DeleteProgram(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProgram", reflect.TypeOf((*MockProgramService)(nil).DeleteProgram), ctx, id)
}

// GetProgram mocks base method.
func (m *MockProgramService) GetProgram(ctx context.Context, id uuid.UUID) (*domain.ProgramWithDepartment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProgram", ctx, id)
	ret0, _ := ret[0].(*domain.ProgramWithDepartment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProgram indicates an expected call of GetProgram.
func (mr *MockProgramServiceMockRecorder) GetProgram(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProgram", reflect.TypeOf((*MockProgramService)(nil).GetProgram), ctx, id)
}

// ListPrograms mocks base method.
func (m *MockProgramService) ListPrograms(ctx context.Context, filter domain.ProgramFilter, page, limit int) ([]*domain.ProgramWithDepartment, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPrograms", ctx, filter, page, limit)
	ret0, _ := ret[0].([]*domain.ProgramWithDepartment)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPrograms indicates an expected call of ListPrograms.
func (mr *MockProgramServiceMockRecorder) ListPrograms(ctx, filter, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPrograms", reflect.TypeOf((*MockProgramService)(nil).ListPrograms), ctx, filter, page, limit)
}

// UpdateProgram mocks base method.
func (m *MockProgramService) UpdateProgram(ctx context.Context, id uuid.UUID, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProgram", ctx, id, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProgram indicates an expected call of UpdateProgram.
func (mr *MockProgramServiceMockRecorder) UpdateProgram(ctx, id, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProgram", reflect.TypeOf((*MockProgramService)(nil).UpdateProgram), ctx, id, updates)
}

// MockSubjectService is a mock of SubjectService interface.
type MockSubjectService struct {
	ctrl     *gomock.Controller
	recorder *MockSubjectServiceMockRecorder
	isgomock struct{}
}

// MockSubjectServiceMockRecorder is the mock recorder for MockSubjectService.
type MockSubjectServiceMockRecorder struct {
	mock *MockSubjectService
}

// NewMockSubjectService creates a new mock instance.
func NewMockSubjectService(ctrl *gomock.Controller) *MockSubjectService {
	mock := &MockSubjectService{ctrl: ctrl}
	mock.recorder = &MockSubjectServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubjectService) EXPECT() *MockSubjectServiceMockRecorder {
	return m.recorder
}

// AddCorequisite mocks base method.
func (m *MockSubjectService) AddCorequisite(ctx context.Context, subjectID, corequisiteID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCorequisite", ctx, subjectID, corequisiteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCorequisite indicates an expected call of AddCorequisite.
func (mr *MockSubjectServiceMockRecorder) AddCorequisite(ctx, subjectID, corequisiteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCorequisite", reflect.TypeOf((*MockSubjectService)(nil).AddCorequisite), ctx, subjectID, corequisiteID)
}

// AddPrerequisite mocks base method.
func (m *MockSubjectService) AddPrerequisite(ctx context.Context, subjectID, prerequisiteID uuid.UUID, isMandatory bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPrerequisite", ctx, subjectID, prerequisiteID, isMandatory)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPrerequisite indicates an expected call of AddPrerequisite.
func (mr *MockSubjectServiceMockRecorder) AddPrerequisite(ctx, subjectID, prerequisiteID, isMandatory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPrerequisite", reflect.TypeOf((*MockSubjectService)(nil).AddPrerequisite), ctx, subjectID, prerequisiteID, isMandatory)
}

// CreateSubject mocks base method.
func (m *MockSubjectService) CreateSubject(ctx context.Context, subject *domain.Subject, prerequisites []domain.SubjectPrerequisite, corequisites []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubject", ctx, subject, prerequisites, corequisites)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSubject indicates an expected call of CreateSubject.
func (mr *MockSubjectServiceMockRecorder) CreateSubject(ctx, subject, prerequisites, corequisites any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubject", reflect.TypeOf((*MockSubjectService)(nil).CreateSubject), ctx, subject, prerequisites, corequisites)
}

// DeleteSubject mocks base method.
func (m *MockSubjectService) DeleteSubject(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubject", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubject indicates an expected call of DeleteSubject.
func (mr *MockSubjectServiceMockRecorder) DeleteSubject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubject", reflect.TypeOf((*MockSubjectService)(nil).DeleteSubject), ctx, id)
}

// GetSubject mocks base method.
func (m *MockSubjectService) GetSubject(ctx context.Context, id uuid.UUID) (*domain.SubjectWithDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubject", ctx, id)
	ret0, _ := ret[0].(*domain.SubjectWithDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubject indicates an expected call of GetSubject.
func (mr *MockSubjectServiceMockRecorder) GetSubject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubject", reflect.TypeOf((*MockSubjectService)(nil).GetSubject), ctx, id)
}

// ListSubjects mocks base method.
func (m *MockSubjectService) ListSubjects(ctx context.Context, filter domain.SubjectFilter, page, limit int) ([]*domain.Subject, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubjects", ctx, filter, page, limit)
	ret0, _ := ret[0].([]*domain.Subject)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSubjects indicates an expected call of ListSubjects.
func (mr *MockSubjectServiceMockRecorder) ListSubjects(ctx, filter, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubjects", reflect.TypeOf((*MockSubjectService)(nil).ListSubjects), ctx, filter, page, limit)
}

// RemoveCorequisite mocks base method.
func (m *MockSubjectService) RemoveCorequisite(ctx context.Context, subjectID, corequisiteID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCorequisite", ctx, subjectID, corequisiteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCorequisite indicates an expected call of RemoveCorequisite.
func (mr *MockSubjectServiceMockRecorder) RemoveCorequisite(ctx, subjectID, corequisiteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCorequisite", reflect.TypeOf((*MockSubjectService)(nil).RemoveCorequisite), ctx, subjectID, corequisiteID)
}

// RemovePrerequisite mocks base method.
func (m *MockSubjectService) RemovePrerequisite(ctx context.Context, subjectID, prerequisiteID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePrerequisite", ctx, subjectID, prerequisiteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemovePrerequisite indicates an expected call of RemovePrerequisite.
func (mr *MockSubjectServiceMockRecorder) RemovePrerequisite(ctx, subjectID, prerequisiteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePrerequisite", reflect.TypeOf((*MockSubjectService)(nil).RemovePrerequisite), ctx, subjectID, prerequisiteID)
}

// UpdateSubject mocks base method.
func (m *MockSubjectService) UpdateSubject(ctx context.Context, id uuid.UUID, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubject", ctx, id, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubject indicates an expected call of UpdateSubject.
func (mr *MockSubjectServiceMockRecorder) UpdateSubject(ctx, id, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubject", reflect.TypeOf((*MockSubjectService)(nil).UpdateSubject), ctx, id, updates)
}

// MockSemesterService is a mock of SemesterService interface.
type MockSemesterService struct {
	ctrl     *gomock.Controller
	recorder *MockSemesterServiceMockRecorder
	isgomock struct{}
}

// MockSemesterServiceMockRecorder is the mock recorder for MockSemesterService.
type MockSemesterServiceMockRecorder struct {
	mock *MockSemesterService
}

// NewMockSemesterService creates a new mock instance.
func NewMockSemesterService(ctrl *gomock.Controller) *MockSemesterService {
	mock := &MockSemesterService{ctrl: ctrl}
	mock.recorder = &MockSemesterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSemesterService) EXPECT() *MockSemesterServiceMockRecorder {
	return m.recorder
}

// CreateSemester mocks base method.
func (m *MockSemesterService) CreateSemester(ctx context.Context, semester *domain.Semester) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSemester", ctx, semester)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSemester indicates an expected call of CreateSemester.
func (mr *MockSemesterServiceMockRecorder) CreateSemester(ctx, semester any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSemester", reflect.TypeOf((*MockSemesterService)(nil).CreateSemester), ctx, semester)
}

// DeleteSemester mocks base method.
func (m *MockSemesterService) DeleteSemester(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSemester", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSemester indicates an expected call of DeleteSemester.
func (mr *MockSemesterServiceMockRecorder) DeleteSemester(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSemester", reflect.TypeOf((*MockSemesterService)(nil).DeleteSemester), ctx, id)
}

// GetCurrentSemester mocks base method.
func (m *MockSemesterService) GetCurrentSemester(ctx context.Context) (*domain.Semester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentSemester", ctx)
	ret0, _ := ret[0].(*domain.Semester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentSemester indicates an expected call of GetCurrentSemester.
func (mr *MockSemesterServiceMockRecorder) GetCurrentSemester(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentSemester", reflect.TypeOf((*MockSemesterService)(nil).GetCurrentSemester), ctx)
}

// GetSemester mocks base method.
func (m *MockSemesterService) GetSemester(ctx context.Context, id uuid.UUID) (*domain.Semester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSemester", ctx, id)
	ret0, _ := ret[0].(*domain.Semester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSemester indicates an expected call of GetSemester.
func (mr *MockSemesterServiceMockRecorder) GetSemester(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSemester", reflect.TypeOf((*MockSemesterService)(nil).GetSemester), ctx, id)
}

// ListSemesters mocks base method.
func (m *MockSemesterService) ListSemesters(ctx context.Context, filter domain.SemesterFilter, page, limit int) ([]*domain.Semester, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSemesters", ctx, filter, page, limit)
	ret0, _ := ret[0].([]*domain.Semester)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSemesters indicates an expected call of ListSemesters.
func (mr *MockSemesterServiceMockRecorder) ListSemesters(ctx, filter, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSemesters", reflect.TypeOf((*MockSemesterService)(nil).ListSemesters), ctx, filter, page, limit)
}

// SetCurrentSemester mocks base method.
func (m *MockSemesterService) SetCurrentSemester(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCurrentSemester", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCurrentSemester indicates an expected call of SetCurrentSemester.
func (mr *MockSemesterServiceMockRecorder) SetCurrentSemester(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCurrentSemester", reflect.TypeOf((*MockSemesterService)(nil).SetCurrentSemester), ctx, id)
}

// UpdateSemester mocks base method.
func (m *MockSemesterService) UpdateSemester(ctx context.Context, id uuid.UUID, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSemester", ctx, id, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSemester indicates an expected call of UpdateSemester.
func (mr *MockSemesterServiceMockRecorder) UpdateSemester(ctx, id, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSemester", reflect.TypeOf((*MockSemesterService)(nil).UpdateSemester), ctx, id, updates)
}

// MockCourseService is a mock of CourseService interface.
type MockCourseService struct {
	ctrl     *gomock.Controller
	recorder *MockCourseServiceMockRecorder
	isgomock struct{}
}

// MockCourseServiceMockRecorder is the mock recorder for MockCourseService.
type MockCourseServiceMockRecorder struct {
	mock *MockCourseService
}

// NewMockCourseService creates a new mock instance.
func NewMockCourseService(ctrl *gomock.Controller) *MockCourseService {
	mock := &MockCourseService{ctrl: ctrl}
	mock.recorder = &MockCourseServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCourseService) EXPECT() *MockCourseServiceMockRecorder {
	return m.recorder
}

// ActivateCourse mocks base method.
func (m *MockCourseService) ActivateCourse(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateCourse", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateCourse indicates an expected call of ActivateCourse.
func (mr *MockCourseServiceMockRecorder) ActivateCourse(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateCourse", reflect.TypeOf((*MockCourseService)(nil).ActivateCourse), ctx, id)
}

// CreateCourse mocks base method.
func (m *MockCourseService) CreateCourse(ctx context.Context, course *domain.Course) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCourse", ctx, course)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCourse indicates an expected call of CreateCourse.
func (mr *MockCourseServiceMockRecorder) CreateCourse(ctx, course any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCourse", reflect.TypeOf((*MockCourseService)(nil).CreateCourse), ctx, course)
}

// DeactivateCourse mocks base method.
func (m *MockCourseService) DeactivateCourse(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateCourse", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateCourse indicates an expected call of DeactivateCourse.
func (mr *MockCourseServiceMockRecorder) DeactivateCourse(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateCourse", reflect.TypeOf((*MockCourseService)(nil).DeactivateCourse), ctx, id)
}

// DeleteCourse mocks base method.
func (m *MockCourseService) DeleteCourse(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCourse", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCourse indicates an expected call of DeleteCourse.
func (mr *MockCourseServiceMockRecorder) DeleteCourse(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCourse", reflect.TypeOf((*MockCourseService)(nil).DeleteCourse), ctx, id)
}

// GetCourse mocks base method.
func (m *MockCourseService) GetCourse(ctx context.Context, id uuid.UUID) (*domain.CourseWithDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourse", ctx, id)
	ret0, _ := ret[0].(*domain.CourseWithDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourse indicates an expected call of GetCourse.
func (mr *MockCourseServiceMockRecorder) GetCourse(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourse", reflect.TypeOf((*MockCourseService)(nil).GetCourse), ctx, id)
}

// GetCourseStudents mocks base method.
func (m *MockCourseService) GetCourseStudents(ctx context.Context, courseID uuid.UUID, status *string, page, limit int) ([]*domain.EnrollmentWithDetails, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourseStudents", ctx, courseID, status, page, limit)
	ret0, _ := ret[0].([]*domain.EnrollmentWithDetails)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCourseStudents indicates an expected call of GetCourseStudents.
func (mr *MockCourseServiceMockRecorder) GetCourseStudents(ctx, courseID, status, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourseStudents", reflect.TypeOf((*MockCourseService)(nil).GetCourseStudents), ctx, courseID, status, page, limit)
}

// ListCourses mocks base method.
func (m *MockCourseService) ListCourses(ctx context.Context, filter domain.CourseFilter, page, limit int) ([]*domain.CourseWithDetails, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCourses", ctx, filter, page, limit)
	ret0, _ := ret[0].([]*domain.CourseWithDetails)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCourses indicates an expected call of ListCourses.
func (mr *MockCourseServiceMockRecorder) ListCourses(ctx, filter, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCourses", reflect.TypeOf((*MockCourseService)(nil).ListCourses), ctx, filter, page, limit)
}

// UpdateCourse mocks base method.
func (m *MockCourseService) UpdateCourse(ctx context.Context, id uuid.UUID, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCourse", ctx, id, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCourse indicates an expected call of UpdateCourse.
func (mr *MockCourseServiceMockRecorder) UpdateCourse(ctx, id, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCourse", reflect.TypeOf((*MockCourseService)(nil).UpdateCourse), ctx, id, updates)
}

// MockFacultyService is a mock of FacultyService interface.
type MockFacultyService struct {
	ctrl     *gomock.Controller
	recorder *MockFacultyServiceMockRecorder
	isgomock struct{}
}

// MockFacultyServiceMockRecorder is the mock recorder for MockFacultyService.
type MockFacultyServiceMockRecorder struct {
	mock *MockFacultyService
}

// NewMockFacultyService creates a new mock instance.
func NewMockFacultyService(ctrl *gomock.Controller) *MockFacultyService {
	mock := &MockFacultyService{ctrl: ctrl}
	mock.recorder = &MockFacultyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFacultyService) EXPECT() *MockFacultyServiceMockRecorder {
	return m.recorder
}

// CreateFaculty mocks base method.
func (m *MockFacultyService) CreateFaculty(ctx context.Context, faculty *domain.Faculty) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFaculty", ctx, faculty)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFaculty indicates an expected call of CreateFaculty.
func (mr *MockFacultyServiceMockRecorder) CreateFaculty(ctx, faculty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFaculty", reflect.TypeOf((*MockFacultyService)(nil).CreateFaculty), ctx, faculty)
}

// DeleteFaculty mocks base method.
func (m *MockFacultyService) DeleteFaculty(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFaculty", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFaculty indicates an expected call of DeleteFaculty.
func (mr *MockFacultyServiceMockRecorder) DeleteFaculty(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFaculty", reflect.TypeOf((*MockFacultyService)(nil).DeleteFaculty), ctx, id)
}

// GetFaculty mocks base method.
func (m *MockFacultyService) GetFaculty(ctx context.Context, id uuid.UUID) (*domain.FacultyWithDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFaculty", ctx, id)
	ret0, _ := ret[0].(*domain.FacultyWithDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFaculty indicates an expected call of GetFaculty.
func (mr *MockFacultyServiceMockRecorder) GetFaculty(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFaculty", reflect.TypeOf((*MockFacultyService)(nil).GetFaculty), ctx, id)
}

// GetFacultyByUserID mocks base method.
func (m *MockFacultyService) GetFacultyByUserID(ctx context.Context, userID uuid.UUID) (*domain.FacultyWithDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFacultyByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.FacultyWithDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFacultyByUserID indicates an expected call of GetFacultyByUserID.
func (mr *MockFacultyServiceMockRecorder) GetFacultyByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFacultyByUserID", reflect.TypeOf((*MockFacultyService)(nil).GetFacultyByUserID), ctx, userID)
}

// GetFacultyCourses mocks base method.
func (m *MockFacultyService) GetFacultyCourses(ctx context.Context, facultyID uuid.UUID, semesterID *uuid.UUID, page, limit int) ([]*domain.FacultyCourse, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFacultyCourses", ctx, facultyID, semesterID, page, limit)
	ret0, _ := ret[0].([]*domain.FacultyCourse)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFacultyCourses indicates an expected call of GetFacultyCourses.
func (mr *MockFacultyServiceMockRecorder) GetFacultyCourses(ctx, facultyID, semesterID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFacultyCourses", reflect.TypeOf((*MockFacultyService)(nil).GetFacultyCourses), ctx, facultyID, semesterID, page, limit)
}

// ListFaculty mocks base method.
func (m *MockFacultyService) ListFaculty(ctx context.Context, filter domain.FacultyFilter, page, limit int) ([]*domain.FacultyWithDetails, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFaculty", ctx, filter, page, limit)
	ret0, _ := ret[0].([]*domain.FacultyWithDetails)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListFaculty indicates an expected call of ListFaculty.
func (mr *MockFacultyServiceMockRecorder) ListFaculty(ctx, filter, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFaculty", reflect.TypeOf((*MockFacultyService)(nil).ListFaculty), ctx, filter, page, limit)
}

// UpdateFaculty mocks base method.
func (m *MockFacultyService) UpdateFaculty(ctx context.Context, id uuid.UUID, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFaculty", ctx, id, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFaculty indicates an expected call of UpdateFaculty.
func (mr *MockFacultyServiceMockRecorder) UpdateFaculty(ctx, id, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFaculty", reflect.TypeOf((*MockFacultyService)(nil).UpdateFaculty), ctx, id, updates)
}

// MockStudentService is a mock of StudentService interface.
type MockStudentService struct {
	ctrl     *gomock.Controller
	recorder *MockStudentServiceMockRecorder
	isgomock struct{}
}

// MockStudentServiceMockRecorder is the mock recorder for MockStudentService.
type MockStudentServiceMockRecorder struct {
	mock *MockStudentService
}

// NewMockStudentService creates a new mock instance.
func NewMockStudentService(ctrl *gomock.Controller) *MockStudentService {
	mock := &MockStudentService{ctrl: ctrl}
	mock.recorder = &MockStudentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudentService) EXPECT() *MockStudentServiceMockRecorder {
	return m.recorder
}

// CreateStudent mocks base method.
func (m *MockStudentService) CreateStudent(ctx context.Context, student *domain.Student) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStudent", ctx, student)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStudent indicates an expected call of CreateStudent.
func (mr *MockStudentServiceMockRecorder) CreateStudent(ctx, student any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStudent", reflect.TypeOf((*MockStudentService)(nil).CreateStudent), ctx, student)
}

// DeleteStudent mocks base method.
func (m *MockStudentService) DeleteStudent(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStudent", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStudent indicates an expected call of DeleteStudent.
func (mr *MockStudentServiceMockRecorder) DeleteStudent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStudent", reflect.TypeOf((*MockStudentService)(nil).DeleteStudent), ctx, id)
}

// GetStudent mocks base method.
func (m *MockStudentService) GetStudent(ctx context.Context, id uuid.UUID) (*domain.StudentWithDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudent", ctx, id)
	ret0, _ := ret[0].(*domain.StudentWithDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudent indicates an expected call of GetStudent.
func (mr *MockStudentServiceMockRecorder) GetStudent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudent", reflect.TypeOf((*MockStudentService)(nil).GetStudent), ctx, id)
}

// GetStudentByUserID mocks base method.
func (m *MockStudentService) GetStudentByUserID(ctx context.Context, userID uuid.UUID) (*domain.StudentWithDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.StudentWithDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentByUserID indicates an expected call of GetStudentByUserID.
func (mr *MockStudentServiceMockRecorder) GetStudentByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentByUserID", reflect.TypeOf((*MockStudentService)(nil).GetStudentByUserID), ctx, userID)
}

// ListStudents mocks base method.
func (m *MockStudentService) ListStudents(ctx context.Context, filter domain.StudentFilter, page, limit int) ([]*domain.StudentWithDetails, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStudents", ctx, filter, page, limit)
	ret0, _ := ret[0].([]*domain.StudentWithDetails)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListStudents indicates an expected call of ListStudents.
func (mr *MockStudentServiceMockRecorder) ListStudents(ctx, filter, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStudents", reflect.TypeOf((*MockStudentService)(nil).ListStudents), ctx, filter, page, limit)
}

// PromoteStudent mocks base method.
func (m *MockStudentService) PromoteStudent(ctx context.Context, id uuid.UUID, newSemester int, cgpa *float64, creditsEarned int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromoteStudent", ctx, id, newSemester, cgpa, creditsEarned)
	ret0, _ := ret[0].(error)
	return ret0
}

// PromoteStudent indicates an expected call of PromoteStudent.
func (mr *MockStudentServiceMockRecorder) PromoteStudent(ctx, id, newSemester, cgpa, creditsEarned any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromoteStudent", reflect.TypeOf((*MockStudentService)(nil).PromoteStudent), ctx, id, newSemester, cgpa, creditsEarned)
}

// UpdateStudent mocks base method.
func (m *MockStudentService) UpdateStudent(ctx context.Context, id uuid.UUID, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStudent", ctx, id, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStudent indicates an expected call of UpdateStudent.
func (mr *MockStudentServiceMockRecorder) UpdateStudent(ctx, id, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStudent", reflect.TypeOf((*MockStudentService)(nil).UpdateStudent), ctx, id, updates)
}

// MockFacultyAssignmentService is a mock of FacultyAssignmentService interface.
type MockFacultyAssignmentService struct {
	ctrl     *gomock.Controller
	recorder *MockFacultyAssignmentServiceMockRecorder
	isgomock struct{}
}

// MockFacultyAssignmentServiceMockRecorder is the mock recorder for MockFacultyAssignmentService.
type MockFacultyAssignmentServiceMockRecorder struct {
	mock *MockFacultyAssignmentService
}

// NewMockFacultyAssignmentService creates a new mock instance.
func NewMockFacultyAssignmentService(ctrl *gomock.Controller) *MockFacultyAssignmentService {
	mock := &MockFacultyAssignmentService{ctrl: ctrl}
	mock.recorder = &MockFacultyAssignmentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFacultyAssignmentService) EXPECT() *MockFacultyAssignmentServiceMockRecorder {
	return m.recorder
}

// AssignFaculty mocks base method.
func (m *MockFacultyAssignmentService) AssignFaculty(ctx context.Context, courseID, facultyID, assignedBy uuid.UUID, role string, isPrimary bool) (*domain.FacultyCourse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignFaculty", ctx, courseID, facultyID, assignedBy, role, isPrimary)
	ret0, _ := ret[0].(*domain.FacultyCourse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignFaculty indicates an expected call of AssignFaculty.
func (mr *MockFacultyAssignmentServiceMockRecorder) AssignFaculty(ctx, courseID, facultyID, assignedBy, role, isPrimary any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignFaculty", reflect.TypeOf((*MockFacultyAssignmentService)(nil).AssignFaculty), ctx, courseID, facultyID, assignedBy, role, isPrimary)
}

// ListCourseFaculty mocks base method.
func (m *MockFacultyAssignmentService) ListCourseFaculty(ctx context.Context, courseID uuid.UUID) ([]*domain.FacultyCourseWithDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCourseFaculty", ctx, courseID)
	ret0, _ := ret[0].([]*domain.FacultyCourseWithDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCourseFaculty indicates an expected call of ListCourseFaculty.
func (mr *MockFacultyAssignmentServiceMockRecorder) ListCourseFaculty(ctx, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCourseFaculty", reflect.TypeOf((*MockFacultyAssignmentService)(nil).ListCourseFaculty), ctx, courseID)
}

// RemoveFaculty mocks base method.
func (m *MockFacultyAssignmentService) RemoveFaculty(ctx context.Context, courseID, facultyID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFaculty", ctx, courseID, facultyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFaculty indicates an expected call of RemoveFaculty.
func (mr *MockFacultyAssignmentServiceMockRecorder) RemoveFaculty(ctx, courseID, facultyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFaculty", reflect.TypeOf((*MockFacultyAssignmentService)(nil).RemoveFaculty), ctx, courseID, facultyID)
}

// UpdateAssignment mocks base method.
func (m *MockFacultyAssignmentService) UpdateAssignment(ctx context.Context, courseID, facultyID uuid.UUID, role string, isPrimary bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAssignment", ctx, courseID, facultyID, role, isPrimary)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAssignment indicates an expected call of UpdateAssignment.
func (mr *MockFacultyAssignmentServiceMockRecorder) UpdateAssignment(ctx, courseID, facultyID, role, isPrimary any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAssignment", reflect.TypeOf((*MockFacultyAssignmentService)(nil).UpdateAssignment), ctx, courseID, facultyID, role, isPrimary)
}

// MockEnrollmentService is a mock of EnrollmentService interface.
type MockEnrollmentService struct {
	ctrl     *gomock.Controller
	recorder *MockEnrollmentServiceMockRecorder
	isgomock struct{}
}

// MockEnrollmentServiceMockRecorder is the mock recorder for MockEnrollmentService.
type MockEnrollmentServiceMockRecorder struct {
	mock *MockEnrollmentService
}

// NewMockEnrollmentService creates a new mock instance.
func NewMockEnrollmentService(ctrl *gomock.Controller) *MockEnrollmentService {
	mock := &MockEnrollmentService{ctrl: ctrl}
	mock.recorder = &MockEnrollmentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnrollmentService) EXPECT() *MockEnrollmentServiceMockRecorder {
	return m.recorder
}

// BulkEnroll mocks base method.
func (m *MockEnrollmentService) BulkEnroll(ctx context.Context, courseID uuid.UUID, studentIDs []uuid.UUID, skipPrerequisites bool) ([]domain.BulkEnrollResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkEnroll", ctx, courseID, studentIDs, skipPrerequisites)
	ret0, _ := ret[0].([]domain.BulkEnrollResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkEnroll indicates an expected call of BulkEnroll.
func (mr *MockEnrollmentServiceMockRecorder) BulkEnroll(ctx, courseID, studentIDs, skipPrerequisites any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkEnroll", reflect.TypeOf((*MockEnrollmentService)(nil).BulkEnroll), ctx, courseID, studentIDs, skipPrerequisites)
}

// CheckPrerequisites mocks base method.
func (m *MockEnrollmentService) CheckPrerequisites(ctx context.Context, studentID, courseID uuid.UUID) (bool, []domain.SubjectBasic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPrerequisites", ctx, studentID, courseID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].([]domain.SubjectBasic)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckPrerequisites indicates an expected call of CheckPrerequisites.
func (mr *MockEnrollmentServiceMockRecorder) CheckPrerequisites(ctx, studentID, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPrerequisites", reflect.TypeOf((*MockEnrollmentService)(nil).CheckPrerequisites), ctx, studentID, courseID)
}

// DropCourse mocks base method.
func (m *MockEnrollmentService) DropCourse(ctx context.Context, courseID, studentID uuid.UUID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DropCourse", ctx, courseID, studentID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// DropCourse indicates an expected call of DropCourse.
func (mr *MockEnrollmentServiceMockRecorder) DropCourse(ctx, courseID, studentID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropCourse", reflect.TypeOf((*MockEnrollmentService)(nil).DropCourse), ctx, courseID, studentID, reason)
}

// EnrollStudent mocks base method.
func (m *MockEnrollmentService) EnrollStudent(ctx context.Context, courseID, studentID uuid.UUID, enrolledBy string) (*domain.CourseEnrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnrollStudent", ctx, courseID, studentID, enrolledBy)
	ret0, _ := ret[0].(*domain.CourseEnrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnrollStudent indicates an expected call of EnrollStudent.
func (mr *MockEnrollmentServiceMockRecorder) EnrollStudent(ctx, courseID, studentID, enrolledBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnrollStudent", reflect.TypeOf((*MockEnrollmentService)(nil).EnrollStudent), ctx, courseID, studentID, enrolledBy)
}

// GetStudentEnrollments mocks base method.
func (m *MockEnrollmentService) GetStudentEnrollments(ctx context.Context, studentID uuid.UUID, filter domain.EnrollmentFilter, page, limit int) ([]*domain.EnrollmentWithDetails, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentEnrollments", ctx, studentID, filter, page, limit)
	ret0, _ := ret[0].([]*domain.EnrollmentWithDetails)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetStudentEnrollments indicates an expected call of GetStudentEnrollments.
func (mr *MockEnrollmentServiceMockRecorder) GetStudentEnrollments(ctx, studentID, filter, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentEnrollments", reflect.TypeOf((*MockEnrollmentService)(nil).GetStudentEnrollments), ctx, studentID, filter, page, limit)
}

// UpdateEnrollment mocks base method.
func (m *MockEnrollmentService) UpdateEnrollment(ctx context.Context, enrollmentID uuid.UUID, status string, grade *string, gradePoints *float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEnrollment", ctx, enrollmentID, status, grade, gradePoints)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEnrollment indicates an expected call of UpdateEnrollment.
func (mr *MockEnrollmentServiceMockRecorder) UpdateEnrollment(ctx, enrollmentID, status, grade, gradePoints any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEnrollment", reflect.TypeOf((*MockEnrollmentService)(nil).UpdateEnrollment), ctx, enrollmentID, status, grade, gradePoints)
}

// MockCalendarService is a mock of CalendarService interface.
type MockCalendarService struct {
	ctrl     *gomock.Controller
	recorder *MockCalendarServiceMockRecorder
	isgomock struct{}
}

// MockCalendarServiceMockRecorder is the mock recorder for MockCalendarService.
type MockCalendarServiceMockRecorder struct {
	mock *MockCalendarService
}

// NewMockCalendarService creates a new mock instance.
func NewMockCalendarService(ctrl *gomock.Controller) *MockCalendarService {
	mock := &MockCalendarService{ctrl: ctrl}
	mock.recorder = &MockCalendarServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCalendarService) EXPECT() *MockCalendarServiceMockRecorder {
	return m.recorder
}

// CreateEvent mocks base method.
func (m *MockCalendarService) CreateEvent(ctx context.Context, event *domain.AcademicCalendarEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockCalendarServiceMockRecorder) CreateEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockCalendarService)(nil).CreateEvent), ctx, event)
}

// DeleteEvent mocks base method.
func (m *MockCalendarService) DeleteEvent(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEvent", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEvent indicates an expected call of DeleteEvent.
func (mr *MockCalendarServiceMockRecorder) DeleteEvent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEvent", reflect.TypeOf((*MockCalendarService)(nil).DeleteEvent), ctx, id)
}

// GetEvent mocks base method.
func (m *MockCalendarService) GetEvent(ctx context.Context, id uuid.UUID) (*domain.AcademicCalendarEventWithDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvent", ctx, id)
	ret0, _ := ret[0].(*domain.AcademicCalendarEventWithDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvent indicates an expected call of GetEvent.
func (mr *MockCalendarServiceMockRecorder) GetEvent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvent", reflect.TypeOf((*MockCalendarService)(nil).GetEvent), ctx, id)
}

// ListEvents mocks base method.
func (m *MockCalendarService) ListEvents(ctx context.Context, filter domain.CalendarFilter, page, limit int) ([]*domain.AcademicCalendarEventWithDetails, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", ctx, filter, page, limit)
	ret0, _ := ret[0].([]*domain.AcademicCalendarEventWithDetails)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockCalendarServiceMockRecorder) ListEvents(ctx, filter, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockCalendarService)(nil).ListEvents), ctx, filter, page, limit)
}

// UpdateEvent mocks base method.
func (m *MockCalendarService) UpdateEvent(ctx context.Context, id uuid.UUID, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvent", ctx, id, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEvent indicates an expected call of UpdateEvent.
func (mr *MockCalendarServiceMockRecorder) UpdateEvent(ctx, id, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvent", reflect.TypeOf((*MockCalendarService)(nil).UpdateEvent), ctx, id, updates)
}

// MockEventProducer is a mock of EventProducer interface.
type MockEventProducer struct {
	ctrl     *gomock.Controller
	recorder *MockEventProducerMockRecorder
	isgomock struct{}
}

// MockEventProducerMockRecorder is the mock recorder for MockEventProducer.
type MockEventProducerMockRecorder struct {
	mock *MockEventProducer
}

// NewMockEventProducer creates a new mock instance.
func NewMockEventProducer(ctrl *gomock.Controller) *MockEventProducer {
	mock := &MockEventProducer{ctrl: ctrl}
	mock.recorder = &MockEventProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventProducer) EXPECT() *MockEventProducerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEventProducer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEventProducerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEventProducer)(nil).Close))
}

// PublishEvent mocks base method.
func (m *MockEventProducer) PublishEvent(topic, key string, event any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishEvent", topic, key, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishEvent indicates an expected call of PublishEvent.
func (mr *MockEventProducerMockRecorder) PublishEvent(topic, key, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishEvent", reflect.TypeOf((*MockEventProducer)(nil).PublishEvent), topic, key, event)
}
